version: '2'
services:
  designmanual:
    image: telemark/designmanual.t-fk.no:latest@sha256:94f03ffb8686847fb9749a00ceb1de70411e76f9c4fc5fdb88c2499ecd85d286
    # build: .
    ports:
      - "3000:3000"
    env_file: designmanual.env
